version: "3"
services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    links:
      - fpm
      - ${DATABASE_ENGINE}

  fpm:
    hostname: ${PHP_FPM_HOST_NAME}
    build:
      context: ./${PHP_VERSION}-fpm
    image: ecomteck/magento2-php:${PHP_VERSION}-fpm
    ports:
      - 9000
    volumes:
      - ${APP_DIR}:/var/www/magento
    links:
      - ${DATABASE_ENGINE}

  mariadb:
    image: mariadb:${MARIADB_VERSION}
    ports:
      - "${MARIADB_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - ${MARIADB_DATA_DIR}:/var/lib/mysql

  mysql:
    image: mysql:${MYSQL_VERSION}
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      - PMA_HOST=${PHPMYADMIN_DATABASE_ENGINE}
      - PMA_PORT=${PHPMYADMIN_DATABASE_PORT}
      - PMA_USER=${PHPMYADMIN_DATABASE_USER}
      - PMA_PASSWORD=${PHPMYADMIN_DATABASE_PASSWORD}

  cli:
    hostname: ${PHP_CLI_HOST_NAME}
    build:
      context: ./${PHP_VERSION}-cli
    image: ecomteck/magento2-php:${PHP_VERSION}-cli
    volumes:
      - ${APP_DIR}:/var/www/magento
    links:
      - ${DATABASE_ENGINE}
    environment:
      - M2SETUP_INSTALL_DB=${M2SETUP_INSTALL_DB}
      - M2SETUP_DB_HOST=${DATABASE_ENGINE}
      - M2SETUP_DB_NAME=${M2SETUP_DB_NAME}
      - M2SETUP_DB_USER=${M2SETUP_DB_USER}
      - M2SETUP_DB_PASSWORD=${M2SETUP_DB_PASSWORD}
      - M2SETUP_BASE_URL=${M2SETUP_BASE_URL}
      - M2SETUP_SECURE_BASE_URL=${M2SETUP_SECURE_BASE_URL}
      - M2SETUP_BACKEND_FRONTNAME=${M2SETUP_BACKEND_FRONTNAME}
      - M2SETUP_ADMIN_FIRSTNAME=${M2SETUP_ADMIN_FIRSTNAME}
      - M2SETUP_ADMIN_LASTNAME=${M2SETUP_ADMIN_LASTNAME}
      - M2SETUP_ADMIN_EMAIL=${M2SETUP_ADMIN_EMAIL}
      - M2SETUP_ADMIN_USER=${M2SETUP_ADMIN_USER}
      - M2SETUP_ADMIN_PASSWORD=${M2SETUP_ADMIN_PASSWORD}
      - M2SETUP_VERSION=${M2SETUP_VERSION}
      - M2SETUP_USE_SAMPLE_DATA=${M2SETUP_USE_SAMPLE_DATA}

  cron:
    build:
      context: ./${PHP_VERSION}-cli
    image: ecomteck/magento2-php:${PHP_VERSION}-cli
    hostname: ${PHP_CRON_HOST_NAME}
    command: run-cron
    environment:
      - ENABLE_SENDMAIL=${ENABLE_SENDMAIL}
    links:
      - ${DATABASE_ENGINE}